"""add_admin_fields_and_usage_events

Revision ID: 30e3a0b7d13b
Revises: 017_mock_interview_sessions
Create Date: 2026-06-01 19:22:53.215119
"""
from alembic import op
import sqlalchemy as sa


revision = '30e3a0b7d13b'
down_revision = '017_mock_interview_sessions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_feature'), 'usage_events', ['feature'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('admin_session_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_session_id')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_feature'), table_name='usage_events')
    op.drop_table('usage_events')
    # ### end Alembic commands ###
