"""add_new_question_types_matching_ordering_fillblank_selectall

Revision ID: 9449496ba921
Revises: 007_add_attempt_caching
Create Date: 2026-05-04 23:53:50.134959
"""
from alembic import op
import sqlalchemy as sa


revision = '9449496ba921'
down_revision = '007_add_attempt_caching'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fill_blank_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('acceptable_answers_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('matching_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pairs_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('ordering_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('correct_order_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('select_all_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('correct_indices_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.drop_constraint('frq_answers_question_id_key', 'frq_answers', type_='unique')
    op.drop_index('ix_frq_answers_question_id', table_name='frq_answers')
    op.create_index(op.f('ix_frq_answers_question_id'), 'frq_answers', ['question_id'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_frq_answers_question_id'), table_name='frq_answers')
    op.create_index('ix_frq_answers_question_id', 'frq_answers', ['question_id'], unique=False)
    op.create_unique_constraint('frq_answers_question_id_key', 'frq_answers', ['question_id'])
    op.drop_table('select_all_answers')
    op.drop_table('ordering_answers')
    op.drop_table('matching_answers')
    op.drop_table('fill_blank_answers')
    # ### end Alembic commands ###
