"""add_upload_status_to_folder_files_and_generation_status_to_tests

Revision ID: d66f3a7e3e9d
Revises: 009_content_hash
Create Date: 2026-05-07 12:15:52.627695
"""
from alembic import op
import sqlalchemy as sa


revision = 'd66f3a7e3e9d'
down_revision = '009_content_hash'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_files', sa.Column('upload_status', sa.String(length=20), nullable=True))
    op.add_column('folder_files', sa.Column('upload_error', sa.Text(), nullable=True))
    op.add_column('tests', sa.Column('generation_status', sa.String(length=20), server_default='ready', nullable=False))
    op.add_column('tests', sa.Column('generation_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'generation_error')
    op.drop_column('tests', 'generation_status')
    op.drop_column('folder_files', 'upload_error')
    op.drop_column('folder_files', 'upload_status')
    # ### end Alembic commands ###
